apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "kubernetesfunctions"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "kubernetesfunctions"
    spec:
      containers:
        - name: "kubernetesfunctions"
          image: "functionapp.azurecr.io/kubernetesfunctions:1.0"
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: "kubernetesfunctions"
    labels:
        app: "kubernetesfunctions"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "kubernetesfunctions"          
